# Alpine Linux based commands
FROM julia:1.10.4-alpine3.20
### RUN apk add --update --no-cache make gcc

# make directories
RUN mkdir -p /tmp
RUN mkdir -p /output
RUN mkdir -p /workspace

# Copy binaries
WORKDIR /
COPY ./ ./


# Prime dependencies for top level script
WORKDIR /
