# ArchLinux based commands
FROM manjarolinux/base:20240804
RUN pacman -Syyu --noconfirm && \
    pacman -S --noconfirm curl && \
    pacman -Scc --noconfirm && \
    rm -f /var/cache/pacman/pkg/*

# make directories
RUN mkdir -p /tmp
RUN mkdir -p /output
RUN mkdir -p /workspace
