# Section `experiment` describes the type of experiment and
# related information such as target variables, data variables, etc.
[experiment]
    name = "Online data analysis for glmmTMB"          # name of the experiment, NOT USED currently

    #target_variable = 4


# Section `linters` enables or disables linters. The format is:
# ```
#   [linters]
#     [linter_name_1] = value_1
#     [linter_name_2] = value_2
#     ...
# ```
# Linters are specified through their name and allowed values are those which can be converted to booleans i.e. `true`/`false` or `0`/`1`.
[linters]
    # Google linters
    datetime_as_string = false
    tokenizable_string = false
    number_as_string = false
    zipcodes_as_values = false
    large_outliers = false
    int_as_float = false
    enum_detector = false
    #enum_detector = false
    uncommon_list_lengths = false
    duplicate_examples = false
    empty_example = false
    #empty_example = false
    uncommon_signs = false
    long_tailed_distrib = false
    circular_domain = false

    # Additional linters
    many_missing_values = false
    negative_values = false
    imbalanced_target_variable = false
    R_glmmTMB_target_variable = true
    R_glmmTMB_binomial_modelling = true


# Section `parameters` gives values to the keyword arguments of the function associated to a specific linter. The format is:
# ```
#   [parameters]
#       [parameters.linter_name]
#           kwarg_1 = value_1
#           kwarg_2 = value_2
#           ...
# ```
# where `kwarg_1`, `kwarg_2` and so on are keyword arguments of the function of the linter named `linter_name`.
[parameters]
    # Google linters
    [parameters.datetime_as_string]
        match_perc = 0.5  # fraction of strings in column that match a date/time format for lint to trigger

    [parameters.tokenizable_string]
        min_tokens = 3    # minimum number of tokens in a string for lint to trigger
        #regexes = ["r\"\\s+\""]  # regexes that split the string into tokens (each regex match is applied separately)
        unused_slot = "a"  # for testing purposes only, will not be used by the data linter

    [parameters.number_as_string]
        match_perc = 0.5  # fraction of strings in column that can be converted to number for lint to trigger

    [parameters.zipcodes_as_values]
        zipcodes=[9000, 9001, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100]
        match_perc = 0.99  # fraction of values in column that match zipcode for lint to trigger

    [parameters.large_outliers]
        tukey_fences_k=10  # larger values consider fewer elements to be anomalous

    [parameters.int_as_float]
        # function is `is_int_as_float`, does not use keyword arguments

    [parameters.enum_detector]
        distinct_ratio=0.001  # if unique column values < (distinct_ratio % of the total number) + 1 => we have an enum
        distinct_max_limit=5  # or if unique column values < distinct_max_limit

    [parameters.uncommon_list_lengths]
        # function is `has_uncommon_list_lengths`, does not use keyword arguments

    [parameters.duplicate_examples]
        # function is `has_duplicates`, does not use keyword arguments

    [parameters.empty_example]
        # function is `is_empty_example`, does not use keyword arguments

    [parameters.uncommon_signs]
        # function is `has_uncommon_signs`, does not use keyword arguments

    [parameters.long_tailed_distrib]
        drop_proportion=0.001  # how many samples % to remove from column before calculating zscores
        zscore_multiplier=5.0  # multiplier for mean zscore; if there are any values with a zscore > mean zscore * multiplier, linter is triggered

    [parameters.circular_domain]
        # function is `has_circular_domain`, does not use keyword arguments

    # Additional linters
    [parameters.many_missing_values]
        threshold = 0.9  # % of values in the columns that have to be mising for the linter to trigger

    [parameters.negative_values]
        # function is `has_negative_values`, does not use keyword arguments

    [parameters.imbalanced_target_variable]
        threshold = 0.1

    [parameters.R_glmmTMB_target_variable]
        threshold = 0.1

    [parameters.R_glmmTMB_binomial_modelling]
        acceptable_link_values = ["logit", "probit", "log-log", "cloglog", "cauchit"]
