#!/bin/sh
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CSV_DIR=$1
KB_DIR=$2
julia -e "
    using Pkg;
    Pkg.activate(\"$SCRIPT_DIR\");
    using Logging;
    using VUBLinter;
    try
        _t = @timed begin
            VUBLinter.cli_linting_workflow(\"$CSV_DIR\", \"$KB_DIR\");
        end
            _, _time, _bytes, _gctime, _ = _t;
            println(\"  Completed in \$_time seconds, \$((_bytes/1024^2)) MB allocated, \$(100*_gctime)% gc time\");
    catch e
    end"
