name: CI
env:
  REPOSITORY_DIR: "./${{ github.event.repository.name }}"  # inside runner
on:
  push:
    branches:
      - master
    tags: '*'
jobs:
  build:
    name: Build DataLinter (${{ github.event_name }})
    runs-on: [self-hosted]
    outputs:
      output1: ${{steps.dateb64.outputs.date}}
    steps:
      - name: Get current date
        id: dateb64
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S' | base64)" >> $GITHUB_OUTPUT

      - name: Checkout current project repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPOSITORY_DIR }}-${{steps.dateb64.outputs.date}}

      - id: build_builder_image
        name: Build datalinter-builder image
        run: |
          cd ${{ env.REPOSITORY_DIR }}-${{ steps.dateb64.outputs.date }}
          docker build --no-cache -f ./docker/debian/Dockerfile.datalinter-builder.debian -t ghcr.io/zgornel/datalinter-builder:debian .
          docker tag ghcr.io/zgornel/datalinter-builder:debian ghcr.io/zgornel/datalinter-builder:latest

      - id: test_datalinter
        name: Test DataLinter
        run: |
          docker run --rm ghcr.io/zgornel/datalinter-builder:latest /julia/bin/julia -e 'using Pkg; Pkg.activate("/DataLinter"); Pkg.test()'

      - id: build_datalinter
        name:  Build DataLinter
        run: |
          cd ${{ env.REPOSITORY_DIR }}-${{ steps.dateb64.outputs.date }}
          mkdir ./julia_packages
          docker run --rm --volume=./build:/DataLinter/build --volume=./julia_packages:/root/.julia/packages ghcr.io/zgornel/datalinter-builder:latest /julia/bin/julia /julia_app_builder/build.jl /DataLinter

      - id: build_datalinter-compiled_image
        name:  Build datalinter-compiled image
        run: |
          cd ${{ env.REPOSITORY_DIR }}-${{ steps.dateb64.outputs.date }}
          docker build --no-cache -f ./docker/debian/Dockerfile.datalinter-compiled.debian -t ghcr.io/zgornel/datalinter-compiled:debian .
          docker tag ghcr.io/zgornel/datalinter-compiled:debian ghcr.io/zgornel/datalinter-compiled:latest
          docker tag ghcr.io/zgornel/datalinter-compiled:debian ghcr.io/zgornel/datalinter-compiled:v0.1.0

      - id: push_datalinter-compiled_image
        name:  Push to ghcr.io datalinter-compiled image
        run: |
          docker push ghcr.io/zgornel/datalinter-compiled:latest
          docker push ghcr.io/zgornel/datalinter-compiled:v0.1.0

      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v6
        with:
          name: datalinter-compiled-binary
          path: ${{ env.REPOSITORY_DIR }}-${{ steps.dateb64.outputs.date }}/build
          compression-level: 9 # high compression (max 9)
          retention-days: 15

      - id: cleanup
        name: Cleanup of Docker containers and images
        run: |
          docker container prune --force
          docker image prune --force
